// GENERATED by scripts/generate-intent-pages.mjs from src/content/intent-pages/manifest.json.
// Do not edit: change the manifest / locale content and re-run the generator.
import type { Metadata } from "next";
import { IntentPage, intentMetadata } from "@/components/intent-page";

const LOCALE = "en" as const;
const SLUG = "deepseek-to-word";

export const metadata: Metadata = intentMetadata(LOCALE, SLUG);

export default function Page() {
  return <IntentPage locale={LOCALE} slug={SLUG} />;
}
