import type { Metadata } from "next";
import Link from "next/link";
import { Footer } from "@/components/footer";
import { RelatedTools } from "@/components/related-tools";
import { LocaleTracker } from "@/components/locale-tracker";
import { IntentDemo } from "@/components/intent-demo";
import { ConverterProvider } from "@/hooks/use-converter";
import { getDictionary, localeMetadata, type Locale } from "@/i18n";
import { safeJsonLd } from "@/lib/json-ld";
import { siteUrl } from "@/lib/site-metadata";
import { findIntentPage, intentGroupAlternates, intentPagePath } from "@/content/intent-pages";

/**
 * Renderer for the data-driven long-tail intent pages (build plan Phase 1).
 * Route stubs (generated by scripts/generate-intent-pages.mjs) call
 * `intentMetadata` and render `<IntentPage>`; all prose lives in
 * src/content/intent-pages/.
 */

const OG_IMAGE = {
  url: "/og-image.png",
  width: 1200,
  height: 630,
  alt: "Markdown Free — Convert Markdown to PDF, Word (DOCX), Image (PNG), EPUB",
};

export function intentMetadata(locale: Locale, slug: string): Metadata {
  const page = findIntentPage(locale, slug);
  if (!page) throw new Error(`intent page not found: ${locale}/${slug}`);
  const path = intentPagePath(page);
  return {
    title: `${page.title} | Markdown Free`,
    description: page.description,
    keywords: page.keywords,
    alternates: {
      canonical: path,
      languages: intentGroupAlternates(page.group),
    },
    openGraph: {
      images: [OG_IMAGE],
      title: page.title,
      description: page.description,
      url: `${siteUrl}${path}`,
      type: "website",
      locale: localeMetadata[locale].ogLocale,
    },
  };
}

export function IntentPage({ locale, slug }: { locale: Locale; slug: string }) {
  const page = findIntentPage(locale, slug);
  if (!page) throw new Error(`intent page not found: ${locale}/${slug}`);
  const dict = getDictionary(locale);
  const home = locale === "en" ? "/" : `/${locale}`;

  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    inLanguage: localeMetadata[locale].htmlLang,
    mainEntity: page.faq.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: { "@type": "Answer", text: item.a },
    })),
  };

  return (
    <ConverterProvider>
      <LocaleTracker locale={locale} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(faqJsonLd) }} />
      <main className="mx-auto flex max-w-3xl flex-col gap-8 px-4 pb-16 pt-10">
        <article className="prose prose-slate max-w-none" data-intent-page={`${page.group}/${page.locale}`}>
          <h1>{page.h1}</h1>
          <p className="lead text-lg text-slate-600">{page.lead}</p>

          <div className="not-prose my-8">
            <Link
              href={home}
              className="inline-flex items-center gap-2 rounded-full bg-emerald-700 px-6 py-3 text-base font-semibold text-white shadow-lg transition hover:bg-emerald-800"
            >
              {page.ctaTop}
              <span aria-hidden="true">→</span>
            </Link>
          </div>

          {page.sections.map((section) => (
            <section key={section.heading}>
              <h2>{section.heading}</h2>
              {section.paragraphs?.map((text, i) => (
                <p key={i}>{text}</p>
              ))}
              {section.steps && (
                <ol>
                  {section.steps.map((step) => (
                    <li key={step.title}>
                      <strong>{step.title}</strong> — {step.text}
                    </li>
                  ))}
                </ol>
              )}
              {section.bullets && (
                <ul>
                  {section.bullets.map((b, i) => (
                    <li key={i}>{b}</li>
                  ))}
                </ul>
              )}
            </section>
          ))}

          {/* Live demo: the exact failing case rendered on this page */}
          <IntentDemo
            locale={locale}
            dict={dict}
            heading={page.demo.heading}
            hint={page.demo.hint}
            readyHint={page.demo.readyHint}
            sampleLabel={page.demo.sampleLabel}
            note={page.demo.note}
            sample={page.sample}
          />

          <h2>{page.faqHeading}</h2>
          {page.faq.map((item) => (
            <div key={item.q}>
              <h3>{item.q}</h3>
              <p>{item.a}</p>
            </div>
          ))}

          <div className="not-prose my-8 rounded-xl border border-emerald-200 bg-emerald-50 p-6 text-center">
            <Link
              href={home}
              className="inline-flex items-center gap-2 rounded-full bg-emerald-700 px-6 py-3 text-base font-semibold text-white shadow-lg transition hover:bg-emerald-800"
            >
              {page.ctaBottom}
              <span aria-hidden="true">→</span>
            </Link>
          </div>

          <RelatedTools locale={locale} current={page.related} />
        </article>

        <Footer locale={locale} dict={dict} />
      </main>
    </ConverterProvider>
  );
}
