// GENERATED by scripts/generate-intent-pages.mjs from src/content/intent-pages/manifest.json.
// Do not edit: change the manifest / locale content and re-run the generator.
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { IntentPage, intentMetadata } from "@/components/intent-page";
import { isValidLocale } from "@/i18n";

const SLUG = "doubao-zhuan-word";
const LOCALES = ["zh-Hans"] as const;

// This page exists only for the locales that publish this slug
export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

function resolve(locale: string) {
  if (!isValidLocale(locale) || !(LOCALES as readonly string[]).includes(locale)) notFound();
  return locale as (typeof LOCALES)[number];
}

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  return intentMetadata(resolve(locale), SLUG);
}

export default async function Page({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  return <IntentPage locale={resolve(locale)} slug={SLUG} />;
}
